version: '3.1'
services:
  php:
    image: yiisoftware/yii2-php:7.1-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - 8000:80
    
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
        MYSQL_DATABASE: blog
        MYSQL_ROOT_PASSWORD: password
        MYSQL_USER: user
        MYSQL_PASSWORD: pass
    volumes:
     - db-data:/var/lib/mysql
    
  adminer:
    image: adminer
    ports:
      - 3307:8080

volumes:
  db-data:
